-- begin TEB12_RUTA
alter table TEB12_RUTA add constraint FK_TEB12_RUTA_ON_PUNTO_INICIO foreign key (PUNTO_INICIO_ID) references TEB12_LOCALIZACION(ID)^
alter table TEB12_RUTA add constraint FK_TEB12_RUTA_ON_PUNTO_FIN foreign key (PUNTO_FIN_ID) references TEB12_LOCALIZACION(ID)^
create index IDX_TEB12_RUTA_ON_PUNTO_INICIO on TEB12_RUTA (PUNTO_INICIO_ID)^
create index IDX_TEB12_RUTA_ON_PUNTO_FIN on TEB12_RUTA (PUNTO_FIN_ID)^
-- end TEB12_RUTA
-- begin TEB12_ROSTER
alter table TEB12_ROSTER add constraint FK_TEB12_ROSTER_ON_OPERADOR foreign key (OPERADOR_ID) references TEB12_UNIDAD_OPERADOR(ID)^
alter table TEB12_ROSTER add constraint FK_TEB12_ROSTER_ON_RUTA foreign key (RUTA_ID) references TEB12_RUTA(ID)^
create index IDX_TEB12_ROSTER_ON_OPERADOR on TEB12_ROSTER (OPERADOR_ID)^
create index IDX_TEB12_ROSTER_ON_RUTA on TEB12_ROSTER (RUTA_ID)^
-- end TEB12_ROSTER
-- begin TEB12_LOCALIZACION
create unique index IDX_TEB12_LOCALIZACION_UNIQ_NOMBRE on TEB12_LOCALIZACION (NOMBRE)^
create unique index IDX_TEB12_LOCALIZACION_UNIQ_CODIGO on TEB12_LOCALIZACION (CODIGO)^
-- end TEB12_LOCALIZACION
-- begin TEB12_UNIDAD
create unique index IDX_TEB12_UNIDAD_UNIQ_UNIDAD on TEB12_UNIDAD (UNIDAD)^
create unique index IDX_TEB12_UNIDAD_UNIQ_MATRICULA on TEB12_UNIDAD (MATRICULA)^
-- end TEB12_UNIDAD
-- begin TEB12_UNIDAD_OPERADOR
alter table TEB12_UNIDAD_OPERADOR add constraint FK_TEB12_UNIDAD_OPERADOR_ON_OPERADOR foreign key (OPERADOR_ID) references TEB12_OPERADOR(ID)^
alter table TEB12_UNIDAD_OPERADOR add constraint FK_TEB12_UNIDAD_OPERADOR_ON_UNIDAD foreign key (UNIDAD_ID) references TEB12_UNIDAD(ID)^
create index IDX_TEB12_UNIDAD_OPERADOR_ON_OPERADOR on TEB12_UNIDAD_OPERADOR (OPERADOR_ID)^
create index IDX_TEB12_UNIDAD_OPERADOR_ON_UNIDAD on TEB12_UNIDAD_OPERADOR (UNIDAD_ID)^
-- end TEB12_UNIDAD_OPERADOR
